observations/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

urlpatterns = [
    path('', LoginUser.as_view(), name='home'),
    # path('index/', index, name='index'),
    path('two_buttons/', buttons, name='buttons'),
    path('success_url/', success, name='success'),
    path('addpage/', AddPage.as_view(), name='add_page'),
    path('observations/', ObservationsListView.as_view(), name='list_observation'),
    path('advanced_observations/', AdvancedListView.as_view(), name='advanced_list'),
    path('manager_observations/', ManagerObservationsListView.as_view(), name='manager_observation'),
    path('employee_observation/', EmployeeObservationsListView.as_view(), name='employee_observation'),
    path('observations/<int:observation_id>/', ObservationDetailView.as_view(), name='detail_observation'),
    path('observations/<int:observation_id>/addition/', ObservationAdditionView.as_view(), name='addition_observation'),
    path('reports/', owner_observation_count, name='report'),
    path('observations/<int:observation_id>/close/', ObservationCloseView.as_view(), name='close_observation'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='observations/password_reset.html'),
         name='reset_password'),
    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name='observations/password_reset_sent.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='observations/password_reset_form.html'),
         name='password_reset_confirm'),
    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='observations/password_reset_done.html'),
         name='password_reset_complete'),
]

setnovo/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from observations.views import *
from setnovo import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('observations.urls')),

]

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = pageNotFound

observations/models.py
from datetime import date
from django.contrib.auth.models import User
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.utils import safestring


placemin = safestring.mark_safe("Место(-)" + "&nbsp;"*17 + "Условия труда не безопасные")
placeplus = safestring.mark_safe("Место(+)" + "&nbsp;"*16 + "Условия труда безопасные")
behaviourmin = safestring.mark_safe("Поведение(-)" + "&nbsp;"*9 + "Поведение не безопасное")
behaviourplus = safestring.mark_safe("Поведение(+)" + "&nbsp;"*8 + "Поведение безопасное")

class StaffGroup(User):
    class Meta:
        proxy = True

    def __str__(self):
        fio = self.last_name + ' ' + self.first_name
        return str(fio)


class Organization(models.Model):
    name = models.TextField("Организация", max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Организация'
        verbose_name_plural = 'Организации'


class Department(models.Model):
    name = models.TextField("Ваш участок", max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Ваш участок'
        verbose_name_plural = 'Ваши участки'
        ordering = ['name']


class Employee(models.Model):
    user = models.OneToOneField(StaffGroup, on_delete=models.PROTECT,
                                verbose_name='Имя сотрудника', related_name='employee')
    users_organization = models.ForeignKey(Organization, on_delete=models.PROTECT, verbose_name='Организация')
    users_department = models.ForeignKey(Department, on_delete=models.PROTECT, verbose_name='Ваш участок')
    responsible_manager = models.ForeignKey(StaffGroup, on_delete=models.PROTECT,
                                            verbose_name='Ответственный руководитель', related_name='manager')
    is_manager = models.BooleanField(verbose_name="Является руководителем(да/нет)", default=False)

    def __str__(self):
        return str(self.user)

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'
        ordering = ['user']


class Category(models.Model):
    name = models.TextField("Категория", max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class View(models.Model):
    name = models.TextField("Вид", max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Вид'
        verbose_name_plural = 'Виды'


class Site(models.Model):
    name = models.ForeignKey(Department, on_delete=models.PROTECT, verbose_name="Участок из ваш участок")
    sites_organisation = models.ForeignKey(Organization, on_delete=models.PROTECT, verbose_name='Организация')
    sites_manager = models.ForeignKey(StaffGroup, on_delete=models.PROTECT, verbose_name='Руководитель участка')

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name = 'Участок наблюдения'
        verbose_name_plural = 'Участки наблюдения'
        ordering = ['name']

class Place(models.Model):
    name = models.TextField("Место наблюдения", max_length=50)
    place_organisation = models.ForeignKey(Organization, on_delete=models.PROTECT,
                                           verbose_name='Организация')
    site_place = models.ForeignKey(Site, on_delete=models.PROTECT,
                                   verbose_name='Участок наблюдения')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Место наблюдения'
        verbose_name_plural = 'Места наблюдения'
        ordering = ['name']


class Control(models.Model):
    name = models.TextField("Конторль", max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Контроль'
        verbose_name_plural = 'Контроль'


class Observation(models.Model):
    """ Наблюдения """

    STATUS_COMPLETED = 'Completed'
    STATUS_REJECTED = 'Rejected'
    STATUS_POSTPONED = 'Postponed'
    STATUS_PROGRESS = 'Progress'
    STATUS_NEW = 'New'

    STATUS_CHOICES = [
        (STATUS_NEW, 'Новое'),
        (STATUS_PROGRESS, 'В работе'),
        (STATUS_POSTPONED, 'Отложено'),
        (STATUS_REJECTED, 'Отклонено'),
        (STATUS_COMPLETED, 'Выполнено'),
    ]

    CHARACTER_CHOICES = (
        ('М-', placemin),
        ('М+', placeplus),
        ('П-', behaviourmin),
        ('П+', behaviourplus),
    )

    CHOICES_BOOLEAN_YES_NO = (
        (True, _('Да')),
        (False, _('Нет'))
    )

    owner = models.ForeignKey(StaffGroup,
                              verbose_name="создатель наблюдения",
                              on_delete=models.PROTECT,
                              related_name='owners', )

    users_organization = models.ForeignKey(Organization,
                                           verbose_name="Организация",
                                           on_delete=models.PROTECT,
                                           related_name='users_organization',
                                           null=True,
                                           blank=True,
                                           default='')

    users_department = models.ForeignKey(Department,
                                         verbose_name="Ваш участок",
                                         on_delete=models.PROTECT,
                                         related_name="users_department",
                                         null=True,
                                         blank=True,
                                         default='')

    date_viewed = models.DateField(verbose_name='Дата наблюдения', default=date.today)

    category = models.ForeignKey(Category,
                                 verbose_name="Категория",
                                 on_delete=models.PROTECT,
                                 related_name='categories')

    character = models.CharField(choices=CHARACTER_CHOICES,
                                 verbose_name="Характер наблюдения",
                                 null=False,
                                 blank=False,
                                 default='',
                                 max_length=35,
                                 )

    dialog = models.BooleanField(verbose_name="Был диалог (да/нет)",
                                 choices=CHOICES_BOOLEAN_YES_NO,
                                 blank=True,
                                 )

    view = models.ForeignKey(View,
                             verbose_name="Вид наблюдения",
                             on_delete=models.PROTECT,
                             related_name='views',
                             null=True,
                             blank=True)
    site = models.ForeignKey(Site,
                              verbose_name="Участок наблюдения",
                              on_delete=models.PROTECT,
                              related_name='sites')

    place = models.ForeignKey(Place,
                             verbose_name="Место наблюдения",
                             on_delete=models.PROTECT,
                             related_name='places',
                             null=True,
                             blank=True
                        )

    description = models.TextField("Описание", max_length=1000)

    probability = models.PositiveSmallIntegerField("Вероятность (от 0 до 5)",
                                                   default=0,
                                                   validators=[MaxValueValidator(5), MinValueValidator(0)],
                                                   null=True)

    effects = models.PositiveSmallIntegerField("Последствия (от 0 до 5)",
                                               default=0,
                                               validators=[MaxValueValidator(5), MinValueValidator(0)],
                                               null=True)

    risk = models.PositiveSmallIntegerField("Уровень риска",
                                            blank=True,
                                            default=0, )

    correction = models.TextField("Улучшение\Влияние", max_length=256, blank=True)

    control = models.ForeignKey(Control,
                                verbose_name="Контроль",
                                on_delete=models.PROTECT,
                                related_name='controls',
                                null=True,
                                blank=True)

    manager = models.ForeignKey(Employee,
                                verbose_name="Ответственный руководитель",
                                on_delete=models.PROTECT,
                                related_name='managers',
                                blank=True,
                                null=True,
                                )

    date_closed_target = models.DateField('Дата закрытия - цель')

    date_closed_fact = models.DateField('Дата закрытия - факт', null=True, blank=True)

    status = models.CharField(verbose_name="Статус",
                              choices=STATUS_CHOICES,
                              max_length=15,
                              default='New')

    date_created = models.DateField(default=date.today)

    corr_action = models.TextField('Корректирующие мероприятия', max_length=512, blank=True)

    photo1 = models.ImageField('Фото1', upload_to='photos/%Y/%m/%d', blank=True)
    photo2 = models.ImageField('Фото2', upload_to='photos/%Y/%m/%d', blank=True)
    photo3 = models.ImageField('Фото3', upload_to='photos/%Y/%m/%d', blank=True)
    photo4 = models.ImageField('Фото4', upload_to='photos/%Y/%m/%d', blank=True)
    photo5 = models.ImageField('Фото5', upload_to='photos/%Y/%m/%d', blank=True)

    class Meta:
        verbose_name = 'Наблюдение по безопасности'

observations/templates/observations/advanced_list.html
{% extends 'observations/base.html' %}
{% block content %}

<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

th, td {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 0px;
}

tr:nth-child(even) {
  background-color: #f77c0f52;
}
</style>

<br>

<div class="row">
    <div class="col">
      <h4 class="text-end">Реестр наблюдений</h4>
    </div>
    <div class="col">
            <h6 class="text-danger">Новых: {{ manager_total.new }}</h6>
            <h6 class="text-success">Открытых: {{ manager_total.open }}</h6>
    </div>
</div>

<!--<div>-->
<!--    <p class="fs-5">Всего отобрано наблюдений: {{ object_list.count }}</p>-->
<!--</div>-->
<div class="col-xl-3 col-md-6 col-sm-12 px-3">
  <form method="GET">
      {{ filter_form.as_table }}
      <button type="submit" class="btn btn-secondary btn-sm" id="submit-id-submit">Применить</button>
  </form>
</div>

<div class="row px-3">
  <div>
      <table
        id = "table"
        data-toggle="table"
        data-filter-control="true"
        data-show-fullscreen="true"
        data-show-filter-control-switch="true"
        data-search="true"
        data-show-export="true"
        data-export-types = ['excel']
        data-search-highlight="true"
        data-show-columns="true"
        data-show-columns-toggle-all="true"
        data-buttons-align="right"
        data-show-footer="true">
        <thead>
              <tr>
                  <th data-footer-formatter="idFormatter">№</th>
                  <th data-field="owner" data-filter-control="select"
                      data-footer-formatter="nameFormatter"
                      data-halign="center">Создатель</th>
                  <th data-field="users_organization" data-filter-control="select" data-halign="center">Организация</th>
                  <th data-field="users_department" data-filter-control="select" data-halign="center">Участок создателя</th>
                  <th data-field="character" data-filter-control="select" data-halign="center">Характер</th>
                  <th data-field="dialog" data-filter-control="select" data-halign="center">Диалог</th>
                  <th data-field="category" data-filter-control="select" data-halign="center">Категория</th>
                  <th data-field="probability" data-filter-control="input" data-halign="center">Вероятность</th>
                  <th data-field="effects" data-filter-control="input" data-halign="center">Последствия</th>
                  <th data-field="risk" data-filter-control="input" data-halign="center">Риск</th>
                  <th data-field="view" data-filter-control="select" data-halign="center">Вид</th>
                  <th data-field="site" data-filter-control="select" data-halign="center">Участок наблюдения</th>
                  {% if users_organization_form_id == 2 %}
                    <th data-field="place" data-filter-control="select" data-halign="center">Место наблюдения</th>
                  {% endif %}
                  <th data-halign="center">Описание</th>
                  <th data-halign="center">Влияние</th>
                  <th data-field="control" data-filter-control="select" data-halign="center">Контроль</th>
                  <th data-field="manager" data-filter-control="select" data-halign="center">Руководитель</th>
                  <th data-field="date_viewed" data-halign="center" data-filter-control="input">Дата наблюдения</th>
                  <th data-field="date_created" data-filter-control="datepicker" data-halign="center">Дата создания</th>
                  <th data-halign="center" data-filter-control="input">Дата закрытия-цель</th>
                  <th data-halign="center" data-filter-control="input">Дата закрытия-факт</th>
                  <th data-halign="center">Корректирующее мероприятие</th>
                  <th data-field="status" data-filter-control="select" data-halign="center">Статус</th>
                  <th data-halign="center">Фото</th>
              </tr>
        </thead>
        <tbody>
                {% for observation in object_list %}
                    <tr>
                          {% if observation.owner == request.user and observation.status != "Completed" %}
                            <td><a href="{% url 'addition_observation' observation.id %}">
                              {{ observation.id }}</a></td>
                          {% elif manager_check == True and observation.status != "Completed" %}
                            <td><a href="{% url 'close_observation' observation.id %}">
                                {{ observation.id }}</a></td>
                          {% else %}
                            <td><a href="{% url 'detail_observation' observation.id %}">
                                {{ observation.id }}</a></td>
                          {% endif %}
                          <td>{{ observation.owner }}</td>
                          <td>{{ observation.users_organization }}</td>
                          <td>{{ observation.users_department }}</td>
                          <td>{{ observation.character }}</td>
                          <td>{{ observation.get_dialog_display}}</td>
                          <td>{{ observation.category }}</td>
                          <td>{{ observation.probability }}</td>
                          <td>{{ observation.effects }}</td>
                           {% if observation.risk < 9 %}
                                <td>{{ observation.risk }}</td>
                           {% elif observation.risk > 8 and observation.risk < 16 %}
                                <td style="background-color:yellow">{{ observation.risk }}</td>
                           {% elif observation.risk > 15 %}
                                <td class="text-bg-danger">{{ observation.risk }}</td>
                           {% endif %}
                          <td>{{ observation.view|default_if_none:"" }}</td>
                          <td>{{ observation.site }}</td>
                          {% if users_organization_form_id == 2 %}
                             <td>{{ observation.place | default_if_none:"" }}</td>
                          {% endif %}
                          <td>{{ observation.description | truncatewords:20 }}</td>
                          <td>{{ observation.correction | truncatewords:5 }}</td>
                          <td>{{ observation.control|default_if_none:"" }}</td>
                          <td>{{ observation.manager }}</td>
                          <td>{{ observation.date_viewed }}</td>
                          <td>{{ observation.date_created }}</td>
                          <td>{{ observation.date_closed_target }}</td>
                          <td>{{ observation.date_closed_fact|default_if_none:"" }}</td>
                          <td>{{ observation.corr_action }}</td>
                              {% if observation.status == "New" %}
                                <td class="text-bg-danger">{{ observation.get_status_display }}</td>
                              {% elif observation.status == "Progress" %}
                                <td style="background-color:yellow">{{ observation.get_status_display }}</td>
                              {% elif observation.status == "Postponed" %}
                                <td style="background-color:orange">{{ observation.get_status_display }}</td>
                              {% elif observation.status == "Rejected" %}
                                <td class="text-bg-secondary">{{ observation.get_status_display }}</td>
                              {% elif observation.status == "Completed" %}
                                <td class="text-bg-success">{{ observation.get_status_display }}</td>
                              {% else %}
                                <td>{{ observation.get_status_display }}</td>
                              {% endif %}

                          {% if observation.photo1 %}
                            <td><img class="img-article-left thumb"
                                   src="{{ observation.photo1.url }}"
                                   width="100%"></td>
                          {% endif %}
                    </tr>
                {% endfor %}
          </tbody>
      </table>
  </div>
</div>
{% endblock %}

observations/templates/observations/detail_observation.html
{% extends 'observations/base.html' %}
{% block content %}

<div class="container">
        <div class="row mb-5">
              <div class="col-xl-2 col-md-6 col-sm-12"></div>
              <div class="col-xl-6 col-md-6 col-sm-12">
              <br><br>
                    {% if observation.status == "Completed" %}
                    <h4 class="text-center text-danger">Наблюдение № {{ observation.pk }} - ЗАКРЫТО</h4>
                    {% else %}
                    <h4 class="text-center text-success">Наблюдение № {{ observation.pk }} - В РАБОТЕ</h4>
                    {% endif %}
              </div>
              <div class="col-xl-4 col-md-6 col-sm-12"></div>
        </div>
</div>
<div class="container">
        <div class="row">
              <div class="col-xl-3 col-md-6 col-sm-12">
              <br>
                 <a href="{% url 'list_observation' %}" class="btn btn-outline-primary" role="button">
                     Реестр наблюдений</a>
                 <br><br>
                 <a href="{% url 'employee_observation' %}" class="btn btn-outline-primary" role="button">
                     Наблюдения для сотрудника</a>
                 <br><br>
                 <a href="{% url 'manager_observation' %}" class="btn btn-outline-primary" role="button">
                     Наблюдения для руководителя</a>
                 <br><br>
                     <a href="{% url 'advanced_list' %}" class="btn btn-outline-primary" role="button">
                     Расширенный реестр</a>
                 <br><br>
                     <a href="{% url 'report' %}" class="btn btn-outline-primary" role="button">Отчёты</a>
              </div>
              <div class="col-xl-9 col-md-12 col-sm-12">
               <table class="table">
                      <tr>
                          <td>Создатель наблюдения:</td>
                          <td>{{ observation.owner }}</td>
                      </tr>
                       <tr>
                          <td>Организация создателя наблюдения:</td>
                          <td>{{ observation.users_organization }}</td>
                      </tr>
                      <tr>
                          <td>Участок создателя наблюдения:</td>
                          <td>{{ observation.users_department }}</td>
                      </tr>
                       <tr>
                          <td>Характер:</td>
                          <td>{{ observation.get_character_display }}</td>
                       </tr>
                       <tr>
                          <td>Был диалог:</td>
                          <td>{{ observation.get_dialog_display}}</td>
                       </tr>
                       <tr>
                          <td>Категория:</td>
                          <td>{{ observation.category }}</td>
                       </tr>
                       <tr>
                          <td>Вероятность:</td>
                          <td>{{ observation.probability }}</td>
                       </tr>
                       <tr>
                          <td>Последствия:</td>
                          <td>{{ observation.effects }}</td>
                       </tr>
                       <tr>
                          <td>Степень риска:</td>
                           {% if observation.risk < 9 %}
                                <td>{{ observation.risk }}</td>
                           {% elif observation.risk > 8 and observation.risk < 16 %}
                                <td style="background-color:yellow">{{ observation.risk }}</td>
                           {% elif observation.risk > 15 %}
                                <td class="text-bg-danger">{{ observation.risk }}</td>
                           {% endif %}
                       </tr>
                       <tr>
                          <td>Вид:</td>
                          <td>{{ observation.view|default_if_none:"" }}</td>
                       </tr>
                       <tr>
                          <td>Участок наблюдения:</td>
                          <td>{{ observation.site }}</td>
                       </tr>
                       {% if observation.users_organization.id == 2 %}
                        <td>Место наблюдения:</td>
                        <td>{{ observation.place|default_if_none:"" }}</td>
                        {% else %}
                        {% endif %}
                       <tr>
                          <td>Описание:</td>
                          <td>{{ observation.description }}</td>
                       </tr>
                       <tr>
                          <td>Влияние:</td>
                          <td>{{ observation.correction }}</td>
                       </tr>
                       <tr>
                          <td>Контроль:</td>
                          <td>{{ observation.control|default_if_none:"" }}</td>
                       </tr>
                       <tr>
                          <td>Руководитель:</td>
                          <td>{{ observation.manager }}</td>
                       </tr>
                      <tr>
                          <td>Дата наблюдения:</td>
                          <td>{{ observation.date_viewed }}</td>
                       </tr>
                      <tr>
                          <td>Дата создания:</td>
                          <td>{{ observation.date_created }}</td>
                       </tr>
                      <tr>
                          <td>Дата закрытия - цель:</td>
                          <td>{{ observation.date_closed_target }}</td>
                       </tr>
                      <tr>
                          <td>Дата закрытия - факт:</td>
                          <td>{{ observation.date_closed_fact|default_if_none:"" }}</td>
                       </tr>
                      <tr>
                          <td>Корректирующее мероприятие:</td>
                          <td>{{ observation.corr_action }}</td>
                       </tr>
                       <tr>
                          <td>Статус:</td>
                              {% if observation.status == "New" %}
                                <td class="text-bg-danger">{{ observation.get_status_display }}</td>
                              {% elif observation.status == "Progress" %}
                                <td style="background-color:yellow">{{ observation.get_status_display }}</td>
                              {% elif observation.status == "Postponed" %}
                                <td style="background-color:orange">{{ observation.get_status_display }}</td>
                              {% elif observation.status == "Rejected" %}
                                <td class="text-bg-secondary">{{ observation.get_status_display }}</td>
                              {% elif observation.status == "Completed" %}
                                <td class="text-bg-success">{{ observation.get_status_display }}</td>
                              {% else %}
                                <td>{{ observation.get_status_display }}</td>
                              {% endif %}
                       </tr>
                       <tr>
                       {% if observation.photo1 %}
                       <td>Фото1:</td>
                       <td><img class="img-article-left thumb" src="{{ observation.photo1.url }}" width="50%"></td>
                       {% endif %}
                       </tr>
                       <tr>
                       {% if observation.photo2 %}
                       <td>Фото2:</td>
                       <td><img class="img-article-left thumb" src="{{ observation.photo2.url }}" width="50%"></td>
                       {% endif %}
                       </tr>
                       <tr>
                       {% if observation.photo3 %}
                       <td>Фото3:</td>
                       <td><img class="img-article-left thumb" src="{{ observation.photo3.url }}" width="50%"></td>
                       {% endif %}
                       </tr>
                       <tr>
                       {% if observation.photo4 %}
                       <td>Фото4:</td>
                       <td><img class="img-article-left thumb" src="{{ observation.photo4.url }}" width="50%"></td>
                       {% endif %}
                       </tr>
                       <tr>
                       {% if observation.photo5 %}
                       <td>Фото5:</td>
                       <td><img class="img-article-left thumb" src="{{ observation.photo5.url }}" width="50%"></td>
                       {% endif %}
                       </tr>
                      </table>
              </div>
        </div>
</div>

{% endblock %}

observations/templates/observations/login_old.html
{% extends 'observations/base.html' %}

{% block content %}

<div class="container">
        <div class="row mb-5">
              <div class="col-xl-1 col-md-6 col-sm-12"></div>
              <div class="col-xl-8 col-md-6 col-sm-12">
                  <h3 class="text-center">Добро пожаловать в систему наблюдений по безопасности!</h3>
                      <br>
                  <h4 class="fw-bolder, text-center">Если вы ещё не зарегистрированы, нажмите
                      <a href="{% url 'register' %}">Регистрация</a></h4>
                      <h4 class="text-center">Для входа, введите Имя пользователя и Пароль ниже</h4>
              </div>
              <div class="col-xl-3 col-md-6 col-sm-12"></div>
        </div>
</div>

<div class="container">
        <div class="row">
            <div class="col-xl-3 col-md-4 col-sm-12"></div>
            <div class="col-xl-5 col-md-6 col-sm-12">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Войти</button>
                </form>
                <br><br>
                Забыли пароль? <a href="{% url 'reset_password' %}">Нажмите сюда!</a>
            </div>
        </div>
</div>

{% endblock %}

observations/templates/observations/password_reset_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ввод нового пароля</title>
</head>
<body>
    <h2>Введите новый пароль!</h2>

    <p>Пожалуйста введите новый пароль дважды, для проверки корректности ввода.</p>

    <form method="post">
        {% csrf_token %}
        {{ form}}
        <button type="submit">Сменить пароль</button>
    </form>
</body>
</html>

observations/templates/observations/password_reset_sent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Письмо с инструкцией по восстановлению пароля</title>
</head>
<body>
<h2>Письмо с инструкцией по восстановлению пароля отправлено</h2>


<p>На указанный адрес электронной почты (если в нашей базе данных есть такой адрес)
    отправлена ссылка на смену пароля. Вы должны получить ее в ближайшее время.</p>

<p>Если вы не получили письмо, пожалуйста, убедитесь, что вы ввели корректный адрес, и проверьте папку со спамом.</p>

</body>
</html>